# Generated by Django 2.0.2 on 2019-06-14 10:01

import app.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagelocation',
            name='last_visited_dt',
            field=app.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
    ]
