# Generated by Django 2.0.2 on 2019-06-14 10:07

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190614_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagelocation',
            name='last_visited_dt',
            field=app.models.AutoDateTimeField(auto_now=True),
        ),
    ]
