# Generated by Django 2.0.2 on 2019-06-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190614_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personagelocation',
            name='last_visited_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
